### PR TITLE
[WIP] Windows Registry mk2

### PR DESCRIPTION
**Pull request by russhwolf**
Rebased and heavily modified from #31 

Spent some time with this over the weekend. Added more types and a bunch of refactors. A number of things including contains/remove operations still not working. Looking for feedback around registry API use in general.  Want to make sure this doesn't break any best practices, and that there won't be any obvious issues interoping from native windows code using the same keys.

### CODE REVIEW

**Comment by r4zzz4k** [comment]
Nice to see this to be picked up, great job!

I'm not seeing any obvious issues. My Win10 setup also passes tests. Wild guess would be that there is something to using Windows Registry from Azure Pipelines, but didn't find anything specific on that yet.

Could you add `--stacktrace` to Gradle invocation on CI builds so that we can at least see what's exactly going wrong? Or am I missing something and trace is available somewhere?

**Comment by russhwolf** [comment]
You can see error stacktraces in the Azure dashboard by clicking on a test [here](https://dev.azure.com/russhwolf/Multiplatform%20Settings/_build/results?buildId=116&view=ms.vss-test-web.build-test-results-tab)

Note that a `clear()` call happens before the tests do any other work, so the fact that the `clear()` test is failing is likely the root cause of the rest of the failures. [That error](https://dev.azure.com/russhwolf/Multiplatform%20Settings/_build/results?buildId=116&view=ms.vss-test-web.build-test-results-tab&runId=604&resultId=100009&paneView=debug) points to a failed assertion on [this line](https://github.com/russhwolf/multiplatform-settings/blob/master/tests/src/commonMain/kotlin/com/russhwolf/settings/BaseSettingsTest.kt#L52), which suggests to me that insertions are working, and the remove test passes so removals are probably also working. So my guess is something silently failing in the clear code when it [iterates through subkeys](https://github.com/russhwolf/multiplatform-settings/blob/feature/windows-registry/multiplatform-settings/src/mingwX64Main/kotlin/com/russhwolf/settings/WindowsSettings.kt#L88-L127)

**Comment by russhwolf** [comment]
Added some debug prints. Yeah there's definitely something going wrong there. Max key length isn't being read correctly

```
com.russhwolf.settings.WindowsSettingsTest.clear STANDARD_OUT
    clear: maxNameLength=0
    clear: iterated 0 times
    clear: clearing keys []
    clear: maxNameLength=0
    clear: found key ?????�
    clear: found key ?????�
    clear: iterated 2 times
    clear: clearing keys [?????�, ?????�]
```

**Comment by russhwolf** [comment]
Turns out I was reading the wrong field and just getting lucky when running locally. Now fixed.

Still want to do a bit of cleanup/refactoring and add a few more platform-specific tests, but at this point expect this to be included in 0.6

**Comment by russhwolf** [comment]
This was rebased and merged as part of 0.6

**Pull request closed without merging**
