### PR TITLE
Add common in memory settings implementation.

### PR DESCRIPTION
**Pull request by terrakok**

### CODE REVIEW

**Comment by russhwolf** [comment]
Thanks for the PR! I'm looking for a bit more context here. Is this doing anything that `MockSettings` in the `multiplatform-settings-test` module can't already do? I want to better understand the need for another in-memory implementation.

**Comment by terrakok** [comment]
Hello! I'd created it when I was experimenting with my pet project and trying to launch on nodejs.  
NodeJs hasn't browser's local storage. I think  in_memory implementation is good idea for runtime storage.

**Comment by terrakok** [comment]
`MockSettings` are for testing. Am i right? My implementation for some cases when I want temporary save some values only for runtime my application.

**Comment by russhwolf** [comment]
`MockSettings` was designed for testing, but fundamentally it's just an in-memory implementation. I'd be interested to hear if it fits your use-case since it's largely doing the same thing. I'd be open to adjusting or renaming that implementation if there's enough need for in-memory outside the context of testing, although I'm not completely convinced of that yet.

As to node in particular, I'm curious if you were able to get it working using this implementation. Currently the project is configured just using `browser()` and not `nodejs()`. That might make it impossible to use from node anyway but I've never tested.

**Comment by terrakok** [comment]
Why settings have to be saved only on disk? What about case when I want to change settings storing place inside my app (in-memory or disk)?  
I think yes, `MockSettings` can help with my case but it need more appropriate name.

**Comment by russhwolf** [comment]
I guess the piece I want to understand is, what are you gaining using an in-memory `Settings` that you couldn't get from just working with `MutableMap` directly? Do you have common code that is in-memory on some platforms and stored on disk on others?

**Comment by terrakok** [comment]
Yes, I can use `MutableMap` directly but 
 1. I like `Settings` interface
 2. I can observe values out the box
 3. I can switch it on disk storage in the future

FYI: it's just my idea without big production needs. I really like your library :+1:

**Comment by russhwolf** [comment]
Ok. If `MockSettings` fits your needs for the moment I'm going to close this and open an issue around whether it should be renamed.

I think I understand your need at this point. Just want to be a little wary of scope creep in general so I'd like to understand if others have similar use-cases before making changes.

**Pull request closed without merging**
