### PR TITLE
Draft: Add flow extensions for all types

### PR DESCRIPTION
**Pull request by russhwolf**
Throwing this up to get API feedback.

Some questions:
1. Is it expected/desirable to have the current value emitted immediately, or should emissions only happen on update? Should that be comfigurable?
2. Is there a channel API that makes sense here so you could write as well as read? Or is Flow sufficient?

CI build will fail due to missing platforms in kotlinx.coroutines.

### CODE REVIEW

**Comment by audkar** [comment]
> Is it expected/desirable to have the current value emitted immediately, or should emissions only happen on update? 

In my usages I use both options. So I would vote definitely yes :) 

> Should that be comfigurable?

Yes. And probably one option should be selected by default. I am not familiar with iOS NSUserDefaults. Buf if their listener behavior matches Android then that could be default option.

----
I will be very happy when `Flow` support gets released :panda_face:

**Comment by russhwolf** [comment]
The [code](https://github.com/russhwolf/multiplatform-settings/blob/0413c50334fc046b3fa854622c68d7336e4b5e8a/multiplatform-settings-coroutines/src/commonMain/kotlin/com/russhwolf/settings/coroutines/CoroutineExtensions.kt) is pretty straightforward so you're welcome to copy it to your own project while you're waiting for an official release.

I'm not too concerned with the platform-specific default behaviors around whether to emit immediately. The existing listener APIs are already consistent there. It's just a question of whether to include [this line](https://github.com/russhwolf/multiplatform-settings/pull/37/files#diff-f70f0eb35a1aff868e4f0603c2ef6a7aR34) to emit immediately at the flow level. I probably will make it configurable, but don't know the best default.

**Comment by russhwolf** [comment]
Another open question I have is how to handle versioning. By default I would want to version this with the rest of the library (and that's what this PR currently does), but there is some risk that a slow coroutines release then blocks releasing the other modules. I don't expect the binary-compatibility story for Kotlin/Native to improve in 1.4, so there's probably some value to having separate versioning for artifacts like this that have external KMP dependencies. But then there's the question of what versioning scheme to use to make it clear which `multiplatform-settings-coroutines` version is compatible with which `multiplatform-settings` and `kotlinx.coroutines` versions.

And a related versioning question: should I maintain two separate parallel versions of this coroutines integration to handle both the standard coroutines release as well as the multithreaded `native-mt` one? Leaning toward yes but that will lead to some maintenance complication.

**Comment by audkar** [comment]
> I'm not too concerned with the platform-specific default behaviors around whether to emit immediately. <...> don't know the best default.

If all native platform doesn't emit initial value, then it might be confusing for developers in case this library would behave differently. But I don't have any other strong arguments for any case. For me it's important that both behavior be available :)

I have my own hacked SharedPreference's coroutines wrapper library. I am always emitting initial value. Was easier/quicker to implement that way. But in some cases I have to use `somePrefFlow.drop(1)` now.

>  don't expect the binary-compatibility story for Kotlin/Native to improve in 1.4

But they promised that (if my memory is not failing me :smile:)

In my honest opinion I think this library is not going to change that much that it would be constrained by coroutines releases. But it is possible to branch-out when such problem occurs and do same thing what coroutines-mt did - release separate version. But until then I would say: keep it stupid simple and have single version.

**Comment by JavierSegoviaCordoba** [comment]
I think it should emit immediately.

I can understand having a separate artifact for coroutines but two for this one is a lot IMO.

**Comment by russhwolf** [comment]
This was released with version 0.7. I opted to stick with the existing emit-immediately behavior. If that's not what you want, you can add `.drop(1)`

**Pull request closed without merging**
